apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      name: go-app
      labels:
        app: go-app
    spec:
      containers:
      - image: digofarias/app:v1
        name: go-app
