apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubia-2-containers
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: digofarias/app:v1
        name: go
      containers:
      - image: nginx:latest
        name: nginx
